export const EVENTS = {
  JOIN_ROOM: 'joinRoom',
  LEAVE_ROOM: 'leaveRoom',
  PLAYER_JOINED: 'playerJoined',
  PLAYER_LEFT: 'playerLeft',
  START_MATCH: 'startMatch',
  PHASE_CHANGED: 'phaseChanged',
  FIRST_DEAL: 'firstDeal',
  CHOOSE_TRUMP: 'chooseTrump',
  TRUMP_SELECTED: 'trumpSelected',
  SECOND_DEAL: 'secondDeal',
  YOUR_TURN: 'yourTurn',
  PLAY_CARD: 'playCard',
  ILLEGAL_MOVE: 'illegalMove',
  CARD_PLAYED: 'cardPlayed',
  TRICK_WINNER: 'trickWinner',
  ROUND_WINNER: 'roundWinner',
  MATCH_WINNER: 'matchWinner',
  CHAT_MESSAGE: 'chatMessage',
  PLAYER_DISCONNECTED: 'playerDisconnected',
  PLAYER_RECONNECTED: 'playerReconnected',
  SPECTATOR_JOINED: 'spectatorJoined',
  ROOM_CLOSED: 'roomClosed',
  SYNC_STATE: 'syncState'
};