CREATE TABLE IF NOT EXISTS players (
    id VARCHAR(50) PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matches (
    id VARCHAR(50) PRIMARY KEY,
    room_code VARCHAR(10) NOT NULL,
    winner_team VARCHAR(2) NOT NULL,
    score_a INTEGER NOT NULL,
    score_b INTEGER NOT NULL,
    played_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS player_stats (
    player_id VARCHAR(50) PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,
    matches_played INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    losses INTEGER DEFAULT 0
);